{{- if eq (include "externalS3.enabled" .) "true" -}}
{{- $ca := include "externalS3.caSecretRef" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: s3-external-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ include "externalS3.host" . }}
  http:
    - retries:
        attempts: 3
        retryOn: '504,gateway-error,connect-failure,refused-stream,5xx'
  {{- if $ca }}
      match:
        - port: 80
  {{- end }}
      route:
        - destination:
            host: {{ include "externalS3.host" . }}
          {{- if $ca }}
            port:
              number: 80
          {{- end }}
      timeout: 10s
{{- end }}
